### ISSUE TITLE
Compatibility with Immutable v4

### ISSUE THREAD

**Issue by szagi3891** [philpl/extendable-immutable#10]
Currently immutablejs developers are preparing a new version of this library (current branch master has version in 4.0.0-rc.2).

Will extendable-immutable they are support the new version of immutablejs?

**Comment by philpl** [comment]
I haven't tested it yet, but since the API / Implementation doesn't seem to have changed, I don't see why this should be a problem :smile:

I'll keep this open and test it in the next few days

**Comment by szagi3891** [comment]
I ask just in case :) I would like to use your library and use it in project and use the latest immutable library.

There is some real risk that this API immutablejs can change and it will spoil the compatibility with your library?

Are you planning to develop this library to use the official API immutablejs ?

**Comment by philpl** [comment]
I just pulled and ran the tests against immutable v4. It still seems to work
