### ISSUE TITLE
Typescript types addition

### ISSUE THREAD

**Issue by nigel-daniels** [philpl/extendable-immutable#19]
Hi, I could not find any typescript definitions for this project so I have had a first attempt at creating them.  The definition can be found [here](https://github.com/nigel-daniels/extendable-immutable-typings).  

Nb. This is my first attempt at creating a definition file, but I hope it's of use.

**Comment by kitten** [comment]
Hey, I'd be happy to help you improve them. I've seen a couple of things that might work better if improved a little :wink:

Maybe you would like to open a PR instead to add the typings to the package directly?

**Comment by nigel-daniels** [comment]
@kitten sure np, I'll set up a PR. 
I know this is a naive implementation so I'm curious to see the improvements, sounds like it will help me on the Typescript journey, thanks :)

**Comment by sandtreader** [comment]
Did Nigel's PR get integrated?  I'm just starting a React/Immutable/Extended-Immutable TypeScript project (what the hell, may as well jump in the deep end ;-) ) and the .d.ts is currently missing.  I can use Nigel's for now (thanks Nigel!) but it would be good if they could be part of the package.
