### ISSUE TITLE
It does not support IE

### ISSUE THREAD

**Issue by sangguk2** [philpl/extendable-immutable#8]
String.prototype.startsWith does not support IE.
There is an alternative code using indexOf.
-> http://stackoverflow.com/questions/30867172/code-not-running-in-ie-11-works-fine-in-chrome

**Comment by philpl** [comment]
Oh snap! I wasn't aware of this. I'll fix this today, once I get to it :)

**Comment by philpl** [comment]
@sangguk2 This should work in 1.3.1 now. Thanks for the report :)

**Comment by sangguk2** [comment]
Unfortunately, Object.assign is not compatible with IE, too.
But I'm sure that it will work after fixing Object.assign.
Sorry for bothering you.
